services:
  _defaults:
    public: true

  prestashop.module.simpay.module:
    class: 'Simpay'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'simpay'
    public: true

  simpay.module:
    alias: 'prestashop.module.simpay.module'

  prestashop.module.simpay.front.payment_client_factory:
    class: 'SimPaypl\PrestaShop\PaymentClientFactory'
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  prestashop.module.simpay.front.payment_client:
    class: 'SimPaypl\PrestaShop\SimPayApiService'
    factory: '@prestashop.module.simpay.front.payment_client_factory'

  prestashop.module.simpay.channel_cache:
    class: 'SimPaypl\PrestaShop\Helper\SimPayChannelCache'
    arguments:
      - '@prestashop.module.simpay.front.payment_client'

  prestashop.module.simpay.payment_attempt_service:
    class: 'SimPaypl\PrestaShop\Service\SimPayPaymentAttemptService'

  prestashop.module.simpay.payment_logger:
    class: 'SimPaypl\PrestaShop\Helper\SimPayLogger'

  prestashop.module.simpay.retry_payment_service:
    class: 'SimPaypl\PrestaShop\Service\SimPayRetryPaymentService'
    arguments:
      - '@simpay.module'
      - '@prestashop.adapter.legacy.context'

  SimPaypl\PrestaShop\Controller\SimpayConfigurationAdminController:
    arguments:
      - '@prestashop.module.simpay.admin.form.simpay_form_data_handler'
      - '@prestashop.module.simpay.channel_cache'
    tags:
      - { name: 'controller.service_arguments' }

  # Demo configuration text form
  prestashop.module.simpay.admin.form.simpay_form_type:
    class: 'SimPaypl\PrestaShop\Form\SimpayFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.simpay.admin.form.simpay_data_configuration:
    class: 'SimPaypl\PrestaShop\Form\SimpayDataConfiguration'
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  prestashop.module.simpay.admin.form.simpay_form_data_provider:
    class: 'SimPaypl\PrestaShop\Form\SimpayFormDataProvider'
    arguments:
      - '@prestashop.module.simpay.admin.form.simpay_data_configuration'

  prestashop.module.simpay.admin.form.simpay_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.simpay.admin.form.simpay_form_data_provider'
      - 'SimPaypl\PrestaShop\Form\SimpayFormType'
      - 'SimpayConfiguration'