simpay_configuration:
  path: /simpay/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'SimPaypl\PrestaShop\Controller\SimpayConfigurationAdminController::configureAction'
    # Needed to work with tab system
    _legacy_controller: 'SimpayConfigurationAdminController'
    _legacy_link: 'SimpayConfigurationAdminController'

simpay_admin_channels:
  path: /simpay/channels
  methods: [GET]
  defaults:
    _controller: 'SimPaypl\PrestaShop\Controller\SimpayConfigurationAdminController::channelsAction'