name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install composer dependencies
        run: composer install --no-dev

      - name: Prepare zip package
        run: |
          mkdir simpay
          cp -r config controllers mails src views composer.json composer.lock config.xml index.php LICENSE logo.png simpay.php simpay
          zip -r simpay-prestashop-${{ github.ref_name }}.zip simpay

      - name: Release
        uses: softprops/action-gh-release@v2
        with: 
          files: simpay-prestashop-${{ github.ref_name }}.zip

